Header 	header

# Fixed-axis roll, in degree. Positive clockwise rotation about the X axis, looking forward.
float32 roll

# Fixed-axis desired roll, in degree. Positive clockwise rotation about the X axis, looking forward.
float32 des_roll

# Fixed-axis pitch, in degree. Positive upwards rotation of the camera nose about the Y axis.
float32 pitch

# Fixed-axis desired pitch, in degree. Positive clockwise rotation about the X axis, looking forward.
float32 des_pitch

# Height from the detected floor
float32 height

# Desired height from the detected floor
float32 des_height
